name: Rust

on:
  pull_request:
  push:
    branches: ["main"]
    paths-ignore:  # Don't run CI when changes are only to the following paths
    - "rita_lab/**" # There are no tests set up for cg-lab. But we can get away with that, since all crucial code is tested in their own crates.

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Test (geogram predicates)
        run: cargo test -p rita --features logging
      - name: Test (robust predicates)
        run: cargo test -p rita --no-default-features --features "std,wasm"

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: fmt
        run: cargo fmt --check -p rita
        continue-on-error: true
      - name: clippy std
        run: cargo clippy -p rita
      - name: clippy wasm
        run: cargo clippy -p rita --no-default-features --features "std,wasm"
